// Import express module
const express = require('express');
// Create an instance of express server for my application
const app = express();
// Import kafka-node module
const kafka = require('kafka-node');

// Get the Consumer and KafkaClient classes from the kafka-node module
const Consumer = kafka.Consumer;
const client = new kafka.KafkaClient({ kafkaHost: 'localhost:9092' });
const cors = require('cors');
require('events').defaultMaxListeners = 100;

// Create a Kafka consumer to listen for messages on topic 'alert5'
const consumer = new Consumer(
  client,
    [{ topic: 'alert5' }],
    { autoCommit: true }

);

// allow cors for the client (UI) domain (here runnin locally on localhost:4200) to prevent api failure due to cross origin issue
app.use(cors({
  origin: 'http://localhost:4200',
  allowedHeaders: 'Content-Type',
  methods: 'GET,POST'
}));

// Define a GET endpoint to send alert details generated by the apache kafka producer to the Front-End UI
app.get('/stream/example', (req, res) => {
  consumer.on('message', function (message) {
    const value = JSON.parse(message.value);
    //const data= {id: message.offset, type: value.type, breachType: value.breachType, reason: value.reason, phone: value.phone, email: value.email}
    const data= {id: message.offset, type: value.ALERT_TYPE, breachType: value.BREACH_TYPE, reason: value.BREACH_TYPE}
    res.write(`${JSON.stringify(data)}`);
    res.end()
  });
})

// Create a new Kafka producer to send the data posted from UI to Kafka topic- 'close-alert'
const producer = new kafka.Producer(client);

app.post('/ams/closeAlert', (req,res) => {
  let body = '';
  req.on('data', (chunk) => {
    body += chunk;
  });
  req.on('end', () => {
    const userData = JSON.parse(body);
    res.send({status: 200, message: 'Alert Closed Successfully'})
    // Send a message to a Kafka topic
    const payload = {
      topic: 'close-alert',
      messages: JSON.stringify(userData),
      partition: 0
    };
    producer.send([payload], function(err, data) {
      if (err) {
        console.error(err);
      } else {
        console.log('Message sent:', data);
      }
    });
  });
})

//Create a new kafka client to listen on the 'compliance-manager-alert' topic
const complianceManagerAlertsClient = new kafka.KafkaClient({ kafkaHost: 'localhost:9092' });
const complianceManagerAlertProducer = new kafka.Producer(complianceManagerAlertsClient);

// create a new consumer to listen on the topic 'close-alert'
const complianceManagerGenerator = new Consumer(
  complianceManagerAlertsClient,
  [{ topic: 'compliance-manager-alert' }],
  { autoCommit: true }
);

app.post('/ams/forwardToComplianceManager', (req,res) => {
  console.log('Here 1')
  let body = '';
  req.on('data', (chunk) => {
    body += chunk;
  });
  req.on('end', () => {
    const userData = JSON.parse(body);
    res.send({status: 200, message: 'Alert sent to the Compliance Manager Successfully'})
    // Construct a payload object with the parsed JSON data and send it to the 'compliance-manager-alert' Kafka topic
    const payload = {
      topic: 'compliance-manager-alert',
      messages: JSON.stringify(userData),
      partition: 0
    };
    // Construct a payload object with the parsed JSON data and send it to the 'compliance-manager-alert' Kafka topic
      complianceManagerAlertProducer.send([payload], function(err, data) {
        if (err) {
          console.error(err);
        } else {
          console.log('Message sent:', data);
        }
      });
  });
})

// Get call to send alert details generated by the producer on topic - example
app.get('/stream/complianceManagerAlerts', (req, res) => {
  complianceManagerGenerator.on('message', function (message) {
    // Extract the required fields from the message and store them in a data object
    const value = JSON.parse(message.value);
    const data= {id: message.offset, type: value.type, breachType: value.breachType}
    //const data= {id: message.offset, type: value.type, breachType: value.breachType, reason: value.reason, phone: value.phone, email: value.email}
    // const data= {id: message.offset, type: value.ALERT_TYPE, breachType: value.BREACH_TYPE, reason: value.BREACH_TYPE}

    // Write the data object as a JSON string to the response stream and end the response
    res.write(`${JSON.stringify(data)}`);
    res.end()
  });
})

// Start the Express server and listen on port 3000
app.listen(3000, () => {
  console.log('Server started on port 3000');
});